<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE menu [
<!ELEMENT menu (meals, beverages)>
<!ELEMENT meals (menuItem*)>
<!ELEMENT beverages (hotBeverages, otherBeverages)>
<!ELEMENT hotBeverages (menuItem*)>
<!ELEMENT otherBeverages (menuItem*)>
<!ELEMENT menuItem (name?, size?, price, description?, imageURL?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT imageURL (#PCDATA)>
]>

<menu>
    <meals>
        <menuItem>
            <name>
                Beetroot and feta salad
            </name>
            <price>
                15.00
            </price>
            <description>
                Suitable for vegetarians, made with fresh beetroot.
            </description>
            <imageURL>
            images/Beetroot-and-feta-salad.png
            </imageURL>
        </menuItem>
        <menuItem>
            <name>
                Sourdough Rye Sandwich
            </name>
            <price>
                18.00
            </price>
            <description>
                Cheese and salad sandwich made with organic, sourdough rye bread
            </description>
            <imageURL>
            images/Sourdough-Rye-Sandwich.jpg
            </imageURL>
        </menuItem>
        <menuItem>
            <name>
                Spinach Pie and Salad
            </name>
            <price>
                20.00
            </price>
            <description>
                Tasty pie with salad
            </description>
            <imageURL>
            images/Spinach-Pie-Salad.jpg
            </imageURL>
        </menuItem>
        <menuItem>
            <name>
                Feta pancakes with salad
            </name>
            <price>
                19.50
            </price>
            <description>
                Tasty pancake filled with feta and salad
            </description>
            <imageURL>
            images/Feta-pancakes-with-salad.jpg
            </imageURL>
        </menuItem>
    </meals>
    <beverages>
        <hotBeverages>
            <menuItem>
                <size>
                    Small    
                </size>
                <price>
                    3.50
                </price>
                <description>
                    For coffee, please inform the staff of the coffee type.
                </description>
                <imageURL>
                images/coffeesmall.jpg
                </imageURL>
            </menuItem>
            <menuItem>
                <size>
                    Regular    
                </size>
                <price>
                    4.00
                </price>
                <description>
                    For coffee, please inform the staff of the coffee type.
                </description>
                <imageURL>
                images/coffeemedium.jpg
                </imageURL>
            </menuItem>
            <menuItem>
                <size>
                    Large    
                </size>
                <price>
                    4.50
                </price>
                <description>
                    For coffee, please inform the staff of the coffee type.
                </description>
                <imageURL>
                images/coffeelarge.jpg
                </imageURL>
            </menuItem>
        </hotBeverages>
        <otherBeverages>
            <menuItem>
                <name>
                    Soda    
                </name>
                <price>
                    3.00
                </price>
                <imageURL>
                images/soda.jpg
                </imageURL>
            </menuItem>
            <menuItem>
                <name>
                    Fresh juice    
                </name>
                <price>
                    6.00
                </price>
                <imageURL>
        images\Freshjuice.jpg
                </imageURL>
            </menuItem>
            <menuItem>
                <name>
                    Bottled water    
                </name>
                <price>
                    2.00
                </price>
                <imageURL>
                images/bottlewater.jpg
                </imageURL>
            </menuItem>
        </otherBeverages>
    </beverages>
</menu>
